file = open("filename.txt", "w")
file.write("my sister is a loser\n")
file.write("my sister is a big loser\n")
file.close()
file = open("filename.txt","a")
file.write("my sister is weird")
file.close()
file = open("filename.txt", "r")
filen = file.readlines()
print(filen)